
plugins {
    id 'java-library'
    id 'maven-publish'
}

apply plugin: 'java-library'
apply plugin: 'maven-publish'

group = 'com.monglife.core'
version = '2.0.3'

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}

jar {
    archiveVersion = version
    destinationDirectory.set(file("./release"))
    enabled(true)
}

publishing {
    publications {
        maven(MavenPublication) {

            from components.java
        }
    }
}